### ISSUE TITLE
Investigar por qué no se pasa el exit code de ctest.js vía casper al servidor

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/tedede#1]

**Comment by diegoefe** [comment]
CasperJS  "1.1.0-beta3" devuelve siempre 0 en casper.exit() y casper.test.done(). Bug arreglado en versión master (al menos en 9785824d8bfa01efbe8b2a7bf9a47d65b21915e3). Cuando actualicen el paquete npm debería andar.
