### ISSUE TITLE
Agregar cobertura a los tests basados en casper

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/tedede#2]
Ver https://github.com/codenautas/tedede/blob/master/docs/tests.md

Agregar análisis de cobertura al test que genere un reporte json en formato istanbul (como el de los test mocha).

**Comment by emilioplatzer** [comment]
Hay unas líneas comentadas de lo que intenté con `istanbul-middleware` creo que la solución podría ir por ahí. 

Hay gente que pidió en distintos issues de istanbul y/o mocha unificadores de cobertura.

**Comment by emilioplatzer** [comment]
Creo que solo falta el #5 para considerar a éste listo.

**Comment by emilioplatzer** [comment]
yo mismo @emilioplatzer, debo contestar esto 

(este comentario es una prueba de labels con mentioning).

**Comment by diegoefe** [comment]
Lo cierro por lo que decís dos comentarios antes

**Comment by emilioplatzer** [comment]
Correcto
