### ISSUE TITLE
Hacer un caso de prueba para modificar un input.list

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/tedede#6]
input.list no se puede modificar

```js
var elemento = document.createElement('input');
elemento.list='id-list'; // da error
```

por lo tanto en el navegador html.input({list: 'id-list'}) también da error. 

Hay que buscar la manera para que se pueda hacer, ya sea encontrando el nombre de la propiedad equivalente o poniendo una característica más en este atributo que indique que hay que hacer un setAttribute (que anda) como con los atributos guionados

**Comment by diegoefe** [comment]
Cuál es la idea de este atributo en input? Qué tipo de control?

**Comment by emilioplatzer** [comment]
Me equivoqué de repositorio. El issue era para js-to-html

Perdón.

**Comment by diegoefe** [comment]
OK, lo borro de acá y lo paso?

**Comment by emilioplatzer** [comment]
Sí
